### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by brettbot7** [inversion-api/inversion-engine#103]

**Comment by brettbot7** [comment]
@gernblandston If you create any tickets please place them under this epic.

**Comment by jzrichardson** [comment]
Let me know what can be assigned to me for documentation!

**Comment by lukasbradley** [comment]
I actually enjoy writing docs.  Please let me know where I can help.

**Comment by brettbot7** [comment]
Will do, @lukasbradley! Thanks
