### ISSUE TITLE
Extend Spring EnableInversion Annotation

### ISSUE THREAD

**Issue by lukasbradley** [inversion-api/inversion-engine#142]
I'd like to slightly change the Spring Enable Inversion annotation and add two new options.

`@EnableInversion`

Attempts to find all APIs and EngineListeners defined as beans, and inject them into the Engine.  A lot of the confusion people have been having is accidentally adding a second EnableInversion tag, which attempts to create a second Engine.  I believe your original intent was to only allow one Engine at a time in any JDK.  Is that acceptable?  Once a single Engine is started, another one will not be allowed...?  A warning will be written to the log, but it won't kill the process as it does now.

```
@EnableInversion(apis = {"firstApi", "secondApi"},
				 listeners = {"firstListener", "secondListener"})
```
				 
Allows for explicit injection of APIs and Listeners that are defined as Spring Beans.  
				 
```
@EnableInversion(apiClasses = {"com.whatever.FirstApi", "com.whatever.SecondApi"},
				 listenerClasses = {"com.whatever.FirstListener", "com.whatever.SecondListener"})
```

Allows for explicit injection of APIs and Listeners by class name.  These APIs and Listeners will need public, no-arg constructors.

These three changes will offer the most Spring-ish entensions to our current structure.

Please let me know your thoughts.

**Comment by wellsb1** [comment]
@lukasbradley I like being able to explicitly specify the wiring but retaining the full auto discovery.  In the context of SpringBoot auto-discovery, a single engine would be normal...but I would say one Engine per traditional web app...but I don't want to program it as a singleton...having SpringBoot treat it as a single occurrence is fine.
