### ISSUE TITLE
Add support for fetching Configuration values from Azure App Configuration

### ISSUE THREAD

**Issue by joao-felipe-santoro** [inversion-api/inversion-engine#167]
I would be a nice addition to the product to incorporate a mechanism to fetch values from Azure App Config

**Comment by wellsb1** [comment]
Thanks for the suggestion! Do you mean setting AzureAppConfig up as a "Db" and querying it like a backend datasource or do you mean loading its root config from AzureAppConfig.

**Comment by wellsb1** [comment]
Ahhhh, I see like Spring Cloud.  Have had the Spring Cloud suggestion before.  Cool, thanks for the feedback!  Love to help you w/ this if you would like to work on it :)

**Comment by cs-joao-felipe** [comment]
Awesome thanks :) just to clear things up , just like we fetch from .env, System env it self, and etc, Azure App Config would be another source.

i would go on by adding a toggle do enable it and add the routine to fetch the vars from Azure App Config within the already existing **getProperty** function

**Comment by wellsb1** [comment]
that makes sense.  Do you think you could write the function to fetch from Azure and I'll refactor the existing code so we can make configuration fetching pluggable and the plug your method in?

**Comment by cs-joao-felipe** [comment]
Sure thing :) will do that ASAP with my colleague and give you a heads up once we have it.

**Comment by cs-joao-felipe** [comment]
@wellsb1 you will find the code on the following branch https://github.com/inversion-api/inversion-engine/tree/jfsp/Issue167

**Comment by cs-joao-felipe** [comment]
Heya there @wellsb,  were you able to take a look at the branch in the comment above ?

**Comment by cs-joao-felipe** [comment]
any news regarding this suggested enhancement ?

**Comment by wellsb1** [comment]
Hey @cs-joao-felipe, I'm so sorry, I did not see these github notifications.  Man I feel terrible. I'm going to jump into this today.

**Comment by wellsb1** [comment]
Also this was a big enough change that I felt I needed to do it in the master branch not 0.8.x maintenance branch. 

Thoughts?
