### ISSUE TITLE
JSArray toString() method implementation missing

### ISSUE THREAD

**Issue by krzaq464** [inversion-api/inversion-engine#209]
Due to lack of toString() method implementation, debugging any app using it is difficult. Couldd you please consider that in a next release ?

**Comment by Slawomir-Wojciechowski** [comment]
Image for reference:

![image](https://user-images.githubusercontent.com/85161106/126327037-1909d338-6c82-433c-aaf3-b213e8aa9562.png)

**Comment by wellsb1** [comment]
Hey guys, thanks for the request.  Something like this came up for Inversion 0.7x if I recall.  When investigating then, it was clear that the IntelliJ debugger does not always "get it right" with toString.  I think we removed a JSNode->JSArray circular dependency to solve it.  As JSArray extends JSNode it does not "need" its own toString method but upon revisiting the documentation it seems that the class must directly override .toString for it to be used by the IntelliJ debugger.  I added .toString to JSArray, and made sure I had the correct IntelliJ settings to enable use of .toString but I don't see any change.  Screenshots below.  

Have you guys run into this before with IntelliJ?  Did you figure out when/why/how IntelliJ seems to sometimes show the toString and others not?  

Code change to JSArray
![image](https://user-images.githubusercontent.com/10075274/126401905-a874a413-b081-4bfe-8934-b815d3957147.png)

Resulting "no change" in the debugger.
![image](https://user-images.githubusercontent.com/10075274/126401786-e107b377-f0dc-4f62-be10-144507de6e29.png)

**Comment by wellsb1** [comment]
So I did some more googling and experimenting and what you are seeing is a feature of IntelliJ.  You can either turn off alternative views for collections in the debugger section OR create a Java Type Renderer of ".toString()" for JSArray.  JSNode should have the exact same behavior is it is a Map and JSArray extends JSNode.  

![image](https://user-images.githubusercontent.com/10075274/126430977-8e3aa6e1-e71e-4e7c-900e-6be19bc0ea65.png)

I experimented with having a direct .toString in JSArray.  It did not change the behavior.  With or without toString in JSArray you will see the toString in the debugger if you disable IntelliJ debugger alternative views for collections and you will see the collection view if it is enabled.  Overriding JSNode.toString() in JSArray does not impact the debugger behavior.

If you guys have discovered something else or if I misunderstood your need, please let me know.  I'm going to close this for now as I believe this is 100% an IntelliJ configuration issue and there is nothing the code here can do to change the behavior outside of that IntelliJ config.  

Make sense?

**Comment by wellsb1** [comment]
I found the solution to this issue in the comments here: https://stackoverflow.com/questions/11189708/is-it-possible-to-tell-intellij-idea-to-automatically-invoke-tostring-on-the-o
